### ISSUE TITLE
Error: Invalid connect options supplied.

### ISSUE THREAD

**Issue by jackylee1** [GodsonRockstar/Building-Realtime-Data-Processing-IoT-Applications-Using-AWS#1]
Error: Invalid connect options supplied.
 after all the operation node app.js shows the error

**Comment by AishwaryaB25** [comment]
Hi Sir, 

im facing an issue similar to what you were facing and I needed help from you.

Background: Im trying to publish a mqtt message from aws lambda function to a topic subscribed in AWS iot Core using node.js script.
I installed the aws-iot-device-sdk and trying to run the lambda function. The index.js function is as given below,

var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
  keyPath: '868b6775bf-private.pem.key',
  certPath: '868b6775bf-certificate.pem.crt',
  caPath: 'AmazonRootCA1.pem',
  clientId: 'Publish_Check',
  region: 'ap-south-1',
  host: 'ack3ewkaxussl-ats.iot.ap-south-1.amazonaws.com'
});


device
  .on('connect', function() {
     console.log('connect');
    // device.subscribe('out');

     device.publish('outTopic', JSON.stringify({ message_id:23,Message:'HelloWorld'}));
    });

     device
     .on('message', function(topic, payload) {
console.log('message', topic, payload.toString());
});

But finally when I try to test in AWS Lambda im facing an error as given below:

{  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'aws-iot-device-sdk'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'aws-iot-device-sdk'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
    "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)",
    "    at internal/main/run_main_module.js:18:47"
  ]
}

Can you please help me how to solve this error?. I would be thankful to you for any suggestions.

Thank you very much!!
